### ISSUE TITLE
Overflow hidden when too many node types.

### ISSUE THREAD

**Issue by Niels-P** [SnowdogApps/magento2-menu#100]
Hi Snowdog,

I'm reporting an issue related to Magento 2.3.4. When I'm clicking on the node type it falls behind the default panel built in the Magento back-end. This is of course not very handy. Could we remove the overflow hidden from the Snowdog panel? I suggest the following;

`#snowdog_menu .panel {
      overflow: visible;
}`

![Screenshot 2020-03-24 at 14 13 46](https://user-images.githubusercontent.com/9845073/77429485-0442b480-6dda-11ea-9893-5eb855722dcf.png)

Thank you!

**Comment by Igloczek** [comment]
Thanks for the report, we investigated it and fixed in #101.
Fix is already released as version 2.10.2.
