### ISSUE TITLE
Category dropdown order

### ISSUE THREAD

**Issue by vseager** [SnowdogApps/magento2-menu#107]
It would be really helpful, especially for sites with a large number of subcategories if the category dropdown was ordered as per the main category tree in `Catalog > Categories`, with the subcategories all listed below the parent category.

The current random order makes it hard to find categories:

![screenshot](https://user-images.githubusercontent.com/2035088/84395033-9d24e700-abf5-11ea-8801-e42d92ca260a.png)

**Comment by Igloczek** [comment]
Hi, thanks for reporting this issue, indeed it looks like something annoying. 

Are you planning to prepare some fix for it or should we put it somewhere on our internal Snowdog to-do list?
