### ISSUE TITLE
Does it support mega-menu structure?

### ISSUE THREAD

**Issue by MagePsycho** [SnowdogApps/magento2-menu#110]
Can this extension be used to show the multi group menus (mega-menu)?

**Comment by Igloczek** [comment]
Sure, it can handle any tree-like structure, but it's up to you to create a frontend for it.

**Comment by MagePsycho** [comment]
Thanks for the prompt reply. Is there any PR for the UI/css?

**Comment by Igloczek** [comment]
Please check the readme - https://github.com/SnowdogApps/magento2-menu#frontend
