### ISSUE TITLE
Image upload option for node

### ISSUE THREAD

**Issue by vseager** [SnowdogApps/magento2-menu#114]
It would be nice to have the option to upload an image to a node. A use case for this would be for a mega menu which contains promotional banners.

This can already be achieved using Cms Block node type, but it can get quite messy to manage, for example if you have a menu with 10 top-level categories, and you want two or three promotional banners within each one. It would be far nicer from a user/content-management perspective if the image could be uploaded directly to the node to avoid having to create separate static blocks.

**Comment by Loxzibit** [comment]
Hi @snowremi, do you have an ETA on this feature?

Thanks

**Comment by snowremi** [comment]
Hi @Loxzibit, this feature is at the end of our queue, after the issues with lower numbers. It's hard to provide an ETA for this one at the moment. Would you like to help us with it?

**Comment by vseager** [comment]
@snowremi We have a project coming that you benefit from this functionality, do you know an ETA to review the above PR?

**Comment by Igloczek** [comment]
We are on it, expect some updates this week.

**Comment by vseager** [comment]
@Igloczek Did you manage to look at this PR?

**Comment by Igloczek** [comment]
As you can see in the #140 the work is going on.
