### ISSUE TITLE
Invalidate full page cache

### ISSUE THREAD

**Issue by vseager** [SnowdogApps/magento2-menu#115]
After you edit the menu with caching enabled, it is necessary to refresh the "Page Cache" before the changes take effect on the frontend.

It would be useful if when the menu is edited the page cache is invalidated so that the admin knows that it required flushing:
https://www.atwix.com/development/managing-cache-programmatically/

**Comment by samk-ml** [comment]
Hi, I am having this issue at the moment, Is there any news on this 70191 being deployed to production?

**Comment by andrzejborkowski** [comment]
@samk-ml yes, this issue has been resolved in menu versions starting from 2.13.0
