### ISSUE TITLE
Magento 2.4 support

### ISSUE THREAD

**Issue by onlinebizsoft** [SnowdogApps/magento2-menu#116]
Will the module be working with latest Magento 2.4.0 release ?

**Comment by Igloczek** [comment]
Hi, thanks for the report.
For sure we are planning to support 2.4, although it might take a while.

For now you can check if everything work as expected using
```
composer require snowdog/module-menu:dev-2.4.0-support
```
Any feedback about some compatibility issues is welcome.

**Comment by Igloczek** [comment]
@bahramdavodi it was PHP 7.4 support, not Magento 2.4.

Anyways, the M2.4 was added in #119

**Comment by Igloczek** [comment]
Released as 2.12.0

**Comment by bahramdavodi** [comment]
@i

> @bahramdavodi it was PHP 7.4 support, not Magento 2.4.
> 
> Anyways, the M2.4 support was added in #119.

Magento 2.4 support PHP 7.4 and it's related
