### ISSUE TITLE
Breadcrumb broken

### ISSUE THREAD

**Issue by cenobitz** [SnowdogApps/magento2-menu#132]
Hi.

1. For now this plugin breakes breadcrumb (not showing categories) for products.

And as You can see http://235p1.test.redchamps.com/category-5/simple-product-118.html

2. It is also not working properly on mobile devices - when You click expand button (TO SHOW SUBMENU) on mobile it expand it and redirect to URL which is not expected behaviour because You got only 1 second to see submenu items.

-----
Tested on fresh installs Magento wer. 2.3.5-p1, mobile chrome and firefox.

Tested without cache and with cache...

After disabling module all issues fixed - breadcrumb full path and basic menu with submenu items working without immidiate redirects.

C.

**Comment by cenobitz** [comment]
only first issue BROKEN BREADCRUMB is stricly related with this extension. Issue 2 is related to redchamps snowdog luma support. Sorry for messing.

**Comment by snowremi** [comment]
Hi @cenobitz, thank you for reporting the issue. Currently, we're working on many different issues, would you like to help us with debugging and solving this one?

**Comment by Igloczek** [comment]
@cenobitz sorry, but this is not a bug, and it's not related to this module, this is how the M2 works out of the box.
Please take a look on this demo store - http://demo-m2.bird.eu/
