### ISSUE TITLE
Wrong composer declaration

### ISSUE THREAD

**Issue by thomas-kl1** [SnowdogApps/magento2-menu#148]
The module is no more compatible with Magento <2.3. Please edit the composer version dependencies according to the code changes.

**Comment by Igloczek** [comment]
Hi, thanks for reporting this issue. Could you provide more details about your problems, point out which part of the code is not working or what kind of issues you are facing?

**Comment by thomas-kl1** [comment]
https://github.com/SnowdogApps/magento2-menu/blob/master/Controller/Adminhtml/Menu/MassDelete.php implements HttpPostActionInterface which is available on Magento 2.3

**Comment by Igloczek** [comment]
Thanks, we will check this out.

**Comment by andrzejborkowski** [comment]
I've created an internal task for that DEV-73418, will take a look at this soon

**Comment by KamilBalwierz** [comment]
Version 2.13.0 has been republished with support for older version removed - hope this solves Your issue (2.13.0 should no longer be suggested for Magento 2.2 and older)
