### ISSUE TITLE
Node type "Category Child" - impossible to set Category.

### ISSUE THREAD

**Issue by vmalyk** [SnowdogApps/magento2-menu#152]
**Pre-condition**:
Magento version: 2.4.1
Snowdog module version: 2.13.0

**Current behavior** 
For "Category Child" no category selector:
<img width="1068" alt="Снимок экрана 2020-12-24 в 13 42 27" src="https://user-images.githubusercontent.com/5318027/103083724-2cbc4100-45ee-11eb-9ecb-54f3f5310230.png">

After research, This type wants to get content value for load children categories, but Data is empty (null in table) and as result rendering is wrong.

**Expected behavior**  
Possible to set parent category for render children in menu.

**Comment by andrzejborkowski** [comment]
hey @vmalyk ! thanks for reporting and fixing the issue, we'll review your changes soon

**Comment by davidwindell** [comment]
Great job @vmalyk :+1:

**Comment by andrzejborkowski** [comment]
This is already in develop, closing the issue
