### ISSUE TITLE
Folder structure when using custom templates

### ISSUE THREAD

**Issue by digiltd** [SnowdogApps/magento2-menu#155]
What is the correct format/structure to use when adding custom templates as mentioned in #84

I have tried:

`Theme_Folder/Snowdog_Menu/templates/menu_identifier/menu/custom/wrapper-with-title.phtml`
`Theme_Folder/Snowdog_Menu/templates/menu_identifier/menu/custom/wrapper.phtml`
`Theme_Folder/Snowdog_Menu/templates/menu_identifier/custom/wrapper.phtml`
`Theme_Folder/Snowdog_Menu/templates/menu_identifier/menu/custom/node_type/wrapper/wrapper.phtml`

Yet I keep getting the "There is no custom submenu (children wrapper) template for this type of node." message.

Note that I can override the default templates based on each menu identifier just fine, but I don't have the ability to choose custom templates in the admin.

Can you please clarify how this feature is used as it looks very useful. Thanks

**Comment by Igloczek** [comment]
`Theme_Folder/Snowdog_Menu/templates/{menu_identifier}/menu/{node_type}/{file_to_overwrite}`

There is no `custom` directory anywhere in the path.

**Comment by Igloczek** [comment]
Sorry, I think you were referring to the default overwrite system, not overwrites per submenu. I'll investigate how it works and get back to you.

**Comment by digiltd** [comment]
Cheers. I found the `custom` dir references in the mr https://github.com/SnowdogApps/magento2-menu/commit/4d6d017ef38190eb3cadec056fbcc51a456f10fb#diff-549b0f433f4e394340b2b0437391aa6151ad7c66da86b3eed87c03a691abf80eR26

**Comment by akai-z** [comment]
@digiltd The menu nodes custom templates documentation is now done.
