### ISSUE TITLE
method return annotation should be changed from array to mixed, it breaks swagger 

### ISSUE THREAD

**Issue by georged89oak3** [SnowdogApps/magento2-menu#158]
https://github.com/SnowdogApps/magento2-menu/blob/4c3b2205d2a4b20149903bb47c612884465baa31/Api/Data/NodeInterface.php#L224

**Comment by andrzejborkowski** [comment]
thank you for reporting, I created internal ticket DEV-75295 to check that and will update you soon

**Comment by akai-z** [comment]
@georged89oak3 The is fix is now done and currently merged into `develop` branch. (It will be added to a new release later.)  
If you have further questions, please let us know.
