### ISSUE TITLE
Magento 2.2 compatibility

### ISSUE THREAD

**Issue by jochhop** [SnowdogApps/magento2-menu#16]
Can the extension be updated to be compatible with Magento 2.2? actually there are only RC versions for this release but soon will be published so I guess it worth to make it compatible

**Comment by dermatz** [comment]
Would be create if the Extension is compatible with Magento 2.2 RC

**Comment by Igloczek** [comment]
Related PR #18

**Comment by DariuszMaciejewski** [comment]
Please update to the version 2.1.0.
