### ISSUE TITLE
[feature request] Any plans for GraphQL endpoints?

### ISSUE THREAD

**Issue by tiberiur** [SnowdogApps/magento2-menu#161]
Hello,

Snowdog_Menu is my go-to menu extension and I use it in almost every project.
Quick question: any plans for GraphQL endpoints?

Thanks for the great work so far!

**Comment by andrzejborkowski** [comment]
hi @tiberiur! Thanks for your feedback, glad to hear you like our module! As for your request, we didn't work on this direction yet, but I created internal ticket DEV-76409 and let you know after we did some research

**Comment by akai-z** [comment]
@tiberiur The GraphQL feature is done.  
(It's currently merged into `develop` branch, and will later be published in a new release.)  
If you have any questions about it, please let us know.
