### ISSUE TITLE
Unable to unfold menu on mobile

### ISSUE THREAD

**Issue by web5exposure** [SnowdogApps/magento2-menu#163]
Magento: 2.4.2
Theme: Porto theme with custom child theme
Newest version of this module
PHP 7.4

I'm unable to unfold a submenu. When I click the arrow, it opens the link of the parent menu item instead of opening the submenu.

![image](https://user-images.githubusercontent.com/73223105/110815066-60704400-828a-11eb-9f70-d6b3ee268074.png)

I guess the `:after` should be replaced with a span element which is placed next to the <a> element of the parent item.
```
ul (main list)
  > li (item)
  > li (item)
    > a (parent link)
    > span (arrow to unfold the submenu)
    > ul (submenu)
```

**Comment by Igloczek** [comment]
This module does not provide ready to use user interface, you should report this issues to your theme authors.
