### ISSUE TITLE
Configurable Product Node Shows £0 Price

### ISSUE THREAD

**Issue by bacondeveloper** [SnowdogApps/magento2-menu#169]
https://github.com/SnowdogApps/magento2-menu/blob/7145aacaf46d16bf19607323c3e23c5952860017/Model/ResourceModel/NodeType/Product.php#L65

We've recently setup configurable products on our websites, and I noticed that the product node price returns 0, this is because configurable products don't have a price, only a link to the simple products that contain the price.

To fix this instead of "final_price" I had to use "min_price". I hope this helps other people too.

**Comment by Igloczek** [comment]
Hi @bacondeveloper thanks for reporting this issue. Did you test how the `min_price` behaves on non-configurable products, is it safe to use in other scenarios?

**Comment by bacondeveloper** [comment]
From what I've tested locally, Simple Product behaves as expected with `min_price`. There are other scenarios I have not tested however, such as Special Prices.

**Comment by bacondeveloper** [comment]
Actually I have just tested Special Price and that works as expected too.

**Comment by Igloczek** [comment]
Nice, are you going to prepare PR with that change?

**Comment by bacondeveloper** [comment]
Sure, is there a procedure for that? Branch Name, Merge to Develop?

**Comment by andrzejborkowski** [comment]
I created internal ticket DEV-77605 to review PR
