### ISSUE TITLE
CRITICAL - Sub-menu items get deleted on save

### ISSUE THREAD

**Issue by vseager** [SnowdogApps/magento2-menu#193]
**Note**: this issue is only reproducible in "dev-develop" but I wanted to raise it just in case it makes it's way into the next release.

When saving a menu, all sub-nodes are deleted except from those nested within the first node.

To reproduce:

* Create a new menu
* Add multiple nodes
* Add nodes within the nodes
* Press "Save"

**Before saving:**
![screenshot-hardcloud2 staging edge-servers com-2021 07 08-15_03_32](https://user-images.githubusercontent.com/2035088/124939164-cd110a80-e000-11eb-9f64-5d857c43fc01.png)

**After saving**
![screenshot-hardcloud2 staging edge-servers com-2021 07 08-15_06_03](https://user-images.githubusercontent.com/2035088/124939161-cbdfdd80-e000-11eb-887c-0d7b6340edc5.png)

**Comment by andrzejborkowski** [comment]
@vseager thanks a lot for reporting the issue, we'll check it asap within our internal ticket (80360) and fix in the develop branch, the next 2.16.0 release won't include the issue

**Comment by akai-z** [comment]
@vseager The fix is now merged into develop branch.  
If you have any questions about it, please let us know.
