### ISSUE TITLE
mobile menu opens main category on click

### ISSUE THREAD

**Issue by template-provider** [SnowdogApps/magento2-menu#195]
hi,
I am using the redchamps extension for luma support. I know this may not be the exact location for getting support but since the redchamps extension is linked here, I am asking for help.
The main problem is described already in https://github.com/redchamps/snowdog-menu-luma-support/issues/1

I have a menu structure like:
- main
  - category 1
    - category 2

On mobile the click on category 1 should open the submenu, but it actually redirects to the category 1.
The link is not deactivated. I cannot find the code to fix this issue, but this might be a problem of the main extension, too.
greetings jan

**Comment by Igloczek** [comment]
Sorry, but this module does not provide any frontend logic, only plain templates, so you need to debug in on your own or wait for feedback from people that are working with Luma theme.

**Comment by vseager** [comment]
@template-provider Please see https://github.com/vseager/magento2-snowdog-menu-luma
