### ISSUE TITLE
loadMenu doesn't fallback on all storeviews

### ISSUE THREAD

**Issue by jeroenalewijns** [SnowdogApps/magento2-menu#197]
When selected all storeviews the LoadMenu function doesn't fallback so you have to use a storeID >=1

**Comment by andrzejborkowski** [comment]
@jeroenalewijns hi, could you please explain more? What is the expected result when Store View = All Store Views set for menu?

**Comment by vestman** [comment]
I just noticed the same issue (`snowdog/module-menu:2.15.0`). If the `All Store Views` option in the `Store View` field is selected then the menu will not be loaded.
![image](https://user-images.githubusercontent.com/564243/127287050-1b00549e-d17c-4d7d-8432-fdf9479503ae.png)

But if I select each store view separately the menu will be loaded.
![image](https://user-images.githubusercontent.com/564243/127287315-a91591ca-9a96-4af0-a04e-a7ab76433c70.png)

**Comment by andrzejborkowski** [comment]
@vestman thanks, now it's clear for m2. I created an internal ticket DEV-80999, we'll try to get it fixed as soon as possible

**Comment by andrzejborkowski** [comment]
@vestman the issue has been resolved already https://github.com/SnowdogApps/magento2-menu/pull/199 and changes already in develop, we'll release them soon as well
