### ISSUE TITLE
Menu item position reverts to zero on save

### ISSUE THREAD

**Issue by helloeverything** [SnowdogApps/magento2-menu#201]
I think there is a bug, after updating to 2.16.0 the menu item position is no longer saved. When I downgraded to 2.15 the problem went away.

### To reproduce
1. Drag menu items to a new order
2. Press save
3. Item order is now random instead of by position
4. Check DB and I see that all the positions (in the snowmenu_node table) are all set at 0

### Tested on
Module version: 2.16.0
Magento: 2.4.2-p1
PHP:  7.4.16

<img width="1591" alt="Screenshot 2021-08-02 at 14 27 58" src="https://user-images.githubusercontent.com/678701/127913191-bcebc0d3-df83-425d-a4cd-bacb1f600300.png">

<img width="1590" alt="Screenshot 2021-08-02 at 14 28 10" src="https://user-images.githubusercontent.com/678701/127913200-c7990078-ccbb-498f-bd05-0bf9ca67d753.png">

<img width="1097" alt="Screenshot 2021-08-02 at 14 40 08" src="https://user-images.githubusercontent.com/678701/127914375-a5c507a8-ac51-4dea-9080-c40f13fbbab5.png">

**Comment by andrzejborkowski** [comment]
Thank you for reporting the issue! I created an internal ticket (DEV-81257), we'll fix this bug as soon as possible

**Comment by akai-z** [comment]
@helloeverything The fix is now merged into `develop` branch, and will be later included in a new release.
If you have any questions about it, please let us know.

**Comment by vestman** [comment]
@akai-z Are you planning a release any time soon? The reason I'm asking is just becaus I'm thinking about patching the current release we have installed, but if it's a release planned then I might wait for it.

Cheers!

**Comment by akai-z** [comment]
@vestman The fix is now published under version [2.17.0](https://github.com/SnowdogApps/magento2-menu/compare/2.16.0...2.17.0).

**Comment by vestman** [comment]
That was quick, I appreciate it!
