### ISSUE TITLE
translation and node per store view

### ISSUE THREAD

**Issue by onlinebizsoft** [SnowdogApps/magento2-menu#204]
I think the module is lacking neccessary feature to support multiple store views

Related to this ticket https://github.com/SnowdogApps/magento2-menu/issues/63

Lets break down some user cases
- if you have multiple lanugages you will want to have different translation for each language especially for custom menu node type
- when you sell on multiple countries, you may have certain different menu item for each store (not whole menu)

**Comment by Igloczek** [comment]
You can have multiple menus, and set it for different store views, that's why there is no translation mechanism, nor other options to set visibility for each node separetly.

**Comment by onlinebizsoft** [comment]
@Igloczek I understand that but it is not good enough for example
- You would be happy to see 1 menu tree only instead of 100 different menu for 100 languages
- when we delete one menu node, we want to do it one time instead of repeating 100 times
- using different menu for each store will make many inconveniences with template implementation

**Comment by onlinebizsoft** [comment]
> you can handle translations in code, if that's the desired behavior for you.

But it doesnt work when we want to use with some custom URL link type for example, each language may have different url translation, not just the title.

**Comment by Igloczek** [comment]
Unfortunalety it's out of scope of our interst, and most likely it will add lots of complexity for the backend and the UI/UX. But if you would like to work on this, we are always open for contributions.

For now I'm closing this thread.

**Comment by onlinebizsoft** [comment]
@Igloczek since it is a valid issue and really need for every mutilple stores installation. So can you add a "feature request" label and leave it open for everyone to discuss?
I have the customization for this already however it comes with some other customization and need to be cleaned up.
I will try to submit a PR for this when we find time.

**Comment by Igloczek** [comment]
Sorry but we have diffrent point of view, we shipped dosen of multistore shops and don't have a feeling that such feature is needed. Also, mentioned before issue didn't get much traction, which means it's not something people from community are requesting a lot.

We keep as open only issues we are going to hande on our own or have interest in being solved.
