### ISSUE TITLE
Category Child Link on mobile results in undefined

### ISSUE THREAD

**Issue by template-provider** [SnowdogApps/magento2-menu#205]
see #65 

I click on the mobile menu a link like "/desinfektion/flachen-instrumentedesinfektion/vliestuch", but it opens the url /undefined.
I cannot find the code, where the link for mobile is generated/followed.
The href in the link itself is correct, but it does not work

**Comment by template-provider** [comment]
ok found the problem .... magento 2 standard use in the menu.js this code
```js
                /**
                 * @param {jQuery.Event} event
                 */
                'click .ui-menu-item:has(a)': function (event) {
                    var target;

                    event.preventDefault();
                    target = $(event.target).closest('.ui-menu-item');
                    target.get(0).scrollIntoView();

                    if (!target.hasClass('level-top') || !target.has('.ui-menu').length) {
                        window.location.href = target.find('> a').attr('href');
                    }
                },
```
the closest li item (and link) with the class "ui-menu-item" is executed.

Just add the class to the div in the category_child.phtml.

I know, that this is not a bug of snowdog, but with the integration of magento 2 this should be documentated.

**Comment by template-provider** [comment]
@andrzejborkowski
Is it possible to add a docu entry for this?

**Comment by Igloczek** [comment]
This module does not provide ready to use UI for storefront, so we are not going to add any single theme specific documentation.
