### ISSUE TITLE
Export doesn't contain all child nodes

### ISSUE THREAD

**Issue by vseager** [SnowdogApps/magento2-menu#206]
When exporting a menu, not all child nodes are included.

## Steps to reproduce

1. Create a new menu
2. Add several nodes
3. Add child nodes to some nodes
4. Save
5. Export menu from menu grid

This example export was exported from the menu in the screenshot below (.yaml remained to .txt for GitHub upload): 
[menu-15.txt](https://github.com/SnowdogApps/magento2-menu/files/6975996/menu-15.txt)

![screenshot-anniehaak staging edge-servers com-2021 08 12-15_00_05](https://user-images.githubusercontent.com/2035088/129210767-3ae6f25c-e3eb-4c6c-afdd-c9fbecd2da0c.png)

**Comment by andrzejborkowski** [comment]
@vseager thank you for reporting the issue, we'll check it soon within an internal ticket DEV-82416

**Comment by akai-z** [comment]
@vseager We were not able to reproduce the issue. (Even with long nested nodes trees and with different node types.)

Could you send us a DB/SQL dump of your menu module DB tables in order to test with their data?  
The DB tables' names are `snowmenu_menu`, `snowmenu_node` and `snowmenu_store`.

**Comment by t-velichko** [comment]
I'm experiencing the same issue. I've created a category with several wrappers and each of the wrapper has category in it. When I'm exporting it there are no children categories in *.yaml file.
