### ISSUE TITLE
Don't print messages about custom nodes templates if they are not set

### ISSUE THREAD

**Issue by Igloczek** [SnowdogApps/magento2-menu#208]
We shouldn't print messages marked on the screenshot, because it can be confusing, since that's an advanced feature.

If there is no custom templates set, just show a disabled select with value "Default" and we are good to go.

![image](https://user-images.githubusercontent.com/5119280/131530481-a3589f2d-9321-4ac6-bf21-b878602fc44c.png)

**Comment by andrzejborkowski** [comment]
Thanks @Igloczek! moving it to DEV-82414
