### ISSUE TITLE
GraphQL: Adjustments, fixes. 

### ISSUE THREAD

**Issue by vmalyk** [SnowdogApps/magento2-menu#209]
Hey!

On overview GraphQL schema I see some missed things and it should be improved and fixed:
1.  type SnowdogMenuNode - implemented all menu types, but it contains some specific fields for current type (like target - it's manageble for External Link only) or schema doesn't specify related content - Cms Block, Category, Product, Cms Page, etc. **Suggestion** - Implement Interface and add types for each MenuNode and resolve related entity. It's possible to implement by additional class TypeResolver and add possibility to register Type resolvers by di.xml (like it's implemented for Product Types  in Magento 2 Catalog GraphQL)
2. Extending GraphQL for New Menu type - If implement TypeResolver, add  interfaces  and register new type resolvers in DI - it looks as easy and flex way for extending. 
2. Target - looks like right type is Boolean for that field. It's checkbox on Menu Node Management. Yes, it's stored as Int, but on getting data you should convert to boolean and add target attribute to link. 
3. Return MenuNodes in SnowdogMenu - it minifies extra calls for getting items.

Please review and it's open for discussion,

**Comment by andrzejborkowski** [comment]
thank you for reporting the issue, I created an internal ticket DEV-82522 and we'll review it soon

**Comment by akai-z** [comment]
@vmalyk
The suggested GraphQL adjustments have been merged into develop branch and will soon be included in a new release.

There were also some additional adjustments other than the suggested ones:
- Added `node_template` and `submenu_template` fields to GraphQL menu node type.
- Added store ID filtering support to menu repository `getList` method.
- Added all menu items list support to GraphQL `snowdogMenus` query.
- Added default store filtering support to GraphQL `snowdogMenus` and `snowdogMenuNodes` queries.
- Set non-nullable fields in GraphQL schema.
- Handled duplicate and empty values in GraphQL `snowdogMenus` query `identifiers` argument.
- Memoized loaded menus in GraphQL menu data provider to improve nodes loading performance.

We also to implement a lists paging feature but instead left it as a to do task that could added in the future.
In case lists paging feature gets implemented, then we would have to remove the nodes list from the `snowdogMenus` query output.

The GraphQL queries have become like this:
```
query SnowdogMenusExample {
  snowdogMenus(identifiers: ["foo", "bar"]) {
    items {
      menu_id
      identifier
      title
      css_class
      creation_time
      update_time
      nodes {
        items {
          node_id
          menu_id
          type
          classes
          parent_id              # Parent node ID
          position
          level
          title
          node_template
          submenu_template
          creation_time
          update_time
          additional_data
          ... on SnowdogMenuNodeContentFieldInterface {
            content
          }
          ... on SnowdogMenuNodeImageFieldInterface {
            image
            image_alt_text
          }
          ... on SnowdogMenuCustomUrlNode {
            target                 # (false for "_self", true for "_blank")
          }
        }
      }
    }
  },
  snowdogMenuNodes(identifier: "foobar") {
    items {
      node_id
      menu_id
      type
      classes
      parent_id              # Parent node ID
      position
      level
      title
      node_template
      submenu_template
      creation_time
      update_time
      additional_data
      ... on SnowdogMenuNodeContentFieldInterface {
        content
      }
      ... on SnowdogMenuNodeImageFieldInterface {
        image
        image_alt_text
      }
      ... on SnowdogMenuCustomUrlNode {
        target                 # (false for "_self", true for "_blank")
      }
    }
  }
}
```
We will update the GraphQL documentation in the wiki page as soon as a new release gets published.

If you have any questions about the changes, please let us know.
