### ISSUE TITLE
Crash when category_child has no valid category

### ISSUE THREAD

**Issue by Echron** [SnowdogApps/magento2-menu#211]
When a node of type category_child has no valid category, the exception that there is no such an entity will make the category crash (disappear). I've created a merge request to improve handling of invalid categories:
#210

**Comment by andrzejborkowski** [comment]
Thanks for reporting the issue and your PR, we'll review it soon within our internal ticket DEV-82621

**Comment by andrzejborkowski** [comment]
Closing the issue since we didn't get any feedback on PR [#210](https://github.com/SnowdogApps/magento2-menu/pull/210)
