### ISSUE TITLE
Default Mega Menu for Luma Theme

### ISSUE THREAD

**Issue by MagePsycho** [SnowdogApps/magento2-menu#213]
Does this module provide a mega menu for the Luma theme?

**Comment by Igloczek** [comment]
@MagePsycho plase check the readme, there is a link to module that adds such compatibility.

**Comment by MagePsycho** [comment]
Gotcha!

**Comment by vseager** [comment]
@MagePsycho Also available for seamless Luma support https://github.com/vseager/magento2-snowdog-menu-luma

**Comment by MagePsycho** [comment]
@vseager I am using your plugin and it works great in Magento `2.4.3-p2`
