### ISSUE TITLE
Add Menu to Hyva theme

### ISSUE THREAD

**Issue by henkvalk** [SnowdogApps/magento2-menu#214]
I installed the Menu and want to add it to Hyva theme. 

So I insert the block to my `app/design/frontend/vendor/theme/Magento_Theme/layout/default.xml`

```
<block name="main-menu" class="Snowdog\Menu\Block\Menu">
    <arguments>
        <argument name="menu" xsi:type="string">mainmenu</argument>
    </arguments>
</block>
```

inside the  `Magento_Theme/templates/html/header.phtml`  I added:
```
<!--Main Navigation-->
<?= $block->getChildHtml('main-menu') ?>
```

But the menu were not display.. Is there something changed?

**Comment by andrzejborkowski** [comment]
Sorry, but this module doesn't provide ready to use interface, I think you should report this issue to the theme vendor.

**Comment by Igloczek** [comment]
Let's keep this open, I'd like to be sure it works fine. @henkvalk I'll reach you next week, I'm on vacation right now.

**Comment by henkvalk** [comment]
Thanks. I saw some other users of Hyva struggling the same issue

**Comment by Igloczek** [comment]
@henkvalk did you check the compat module that Vinai created?

https://gitlab.hyva.io/hyva-themes/hyva-compat/magento2-snowdog-menu

**Comment by henkvalk** [comment]
@Igloczek Thanks for sharing. I will take a look at it !

**Comment by vasilii-b** [comment]
Was able to have a working menu with Hyva theme w/o any additional compatibility modules required.
