### ISSUE TITLE
Node Templates by multi store not available

### ISSUE THREAD

**Issue by FFinke-leo** [SnowdogApps/magento2-menu#215]
Hi there

I have a Magento Multi-Store Shop and use your Snowdog Menu Extension. 
My Problem is, I haven't all templates for the node (for example Wrapper) in all themes and the Backend says that there are no node templates. 
If I select the default theme and assign the theme with the templates to this all node templates are available. 
Is it possible to change the code so, that you are watching the selected theme folder and not only the theme, which is selected by the Default/Global Theme. 

Best regards

**Comment by Igloczek** [comment]
Do you have problem with actual rendering of the templates on the frontend, or just assuming something is wrong, because in admin area you see that it print a message about no templates to pick? If the second option, it's just an confusing message that we are about to remove - https://github.com/SnowdogApps/magento2-menu/issues/208

**Comment by Igloczek** [comment]
An option to pick a custom template from any theme in any menu, enough for you? Otherwise, we will have to bind the menu to the theme, which is not something we would like to do.

**Comment by andrzejborkowski** [comment]
@FFinke-leo could you please provide feedback for the question above? Otherwise, we'll need to close the ticket due to the lack of activity. Thanks!

**Comment by HelenD-BID** [comment]
Hello, I am experiencing this same problem.
Trying to add custom sub menu templates when using multi-store with different themes isn't working, my custom templates only show when I set the global store theme.
Is there a workaround/fix for this that I'm missing?
Thank you

**Comment by HelenD-BID** [comment]
> An option to pick a custom template from any theme in any menu, enough for you? Otherwise, we will have to bind the menu to the theme, which is not something we would like to do.

Hello, Was there ever a fix for this? Im experiencing the same issue.
Thank you
