### ISSUE TITLE
After deleting all children of a node you can not add a new child

### ISSUE THREAD

**Issue by MarianNapi** [SnowdogApps/magento2-menu#218]
Let's say you have this structure:

Root
- A
- - A1
- - A2
- B
- - B1
- - B2

If you now delete Children A1 and A2 and try to add a new Child to A you get a vue error:

`Error in v-on handler: "TypeError: Cannot read properties of undefined (reading 'image')"`

If you now add a Child To B there is no error if you try to add a Child to A again.

This also happens if you only have a root node and delete that -> you now can't add a single node.

**Comment by andrzejborkowski** [comment]
@MarianNapi I can't replicate the issue with the latest 2.17.0 tag. What node types did you use for parent/child nodes?

**Comment by oneserv-heuser** [comment]
@andrzejborkowski I can also confirm this issue. 
Here are the steps to reproduce with images:
1. **Click on "Create new menu"**
2. **Click on the "+" symbol (marked with red circle)**
![image](https://user-images.githubusercontent.com/53174153/135041422-2fb34c27-7aaf-451c-b092-6d6ae235ec21.png)
3. **Delete the newly created node**
![image](https://user-images.githubusercontent.com/53174153/135041558-8b6dabbc-7cfa-44ad-8bde-c4eaf42c3054.png)
4. **Repeat step 2**

### Result
No new node can be created. Instead, an error occurs in the console.
![image](https://user-images.githubusercontent.com/53174153/135041673-493b8741-eb65-48b1-8cf5-34a3b100139a.png)

**Comment by andrzejborkowski** [comment]
Thanks for confirming the steps on how to replicate the issue, now I can see the error in console. However when clicking on "+" once again to add a new node it works as expected and you can save the menu. Anyway, I created an internal ticket DEV-83022 and we'll check the issue with our dev team.

**Comment by andrzejborkowski** [comment]
This issue has been fixed already in the latest 2.18.0 release, so I'm closing the ticket
