### ISSUE TITLE
GraphQL - Missing URL information for the Categories nodes

### ISSUE THREAD

**Issue by LucasCalazans** [SnowdogApps/magento2-menu#225]
Sup guys,

I'm using this module for a PWA Studio project so that I'm also using the GraphQL APIs.

I created the logic to fetch the data, but we don't have a field that returns the url_key of the category.

My suggestion is to add a new field called **url_key** inside the node interface related to categories and Childs

**Comment by andrzejborkowski** [comment]
Could you please create a PR with the mentioned changes and after we check it we can merge your changes to develop?

**Comment by texboy** [comment]
Hey @andrzejborkowski, I created a pull request for this feature (I work with @LucasCalazans). It's not the best solution, but I didn't have time to really look into the module and see if there was an easier/more elegant way to do it. Hope this works for you. If not, let me know how I can improve the code.

**Comment by andrzejborkowski** [comment]
thanks a lot for your contribution! I created an internal ticket DEV-85572 and our dev team will review your PR soon.

**Comment by andrzejborkowski** [comment]
@texboy hey, could you please follow suggestions from our dev and apply changes requested in your [PR](https://github.com/SnowdogApps/magento2-menu/pull/227#discussion_r777859747)? Thanks in advance!
