### ISSUE TITLE
Module does not work when database tables have prefixes

### ISSUE THREAD

**Issue by alexvandervegt** [SnowdogApps/magento2-menu#23]
The module does not work when you have table prefixes like:

Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'databasename.eav_attribute' doesn't exist, query was: SELECT `a`.`attribute_id` FROM `eav_attribute` AS `a`

This should be:
databasename.eav_attribute => databasename.prefix_eav_attribute

**Comment by DariuszMaciejewski** [comment]
@alexvandervegt  thank you for your report.

**Comment by DariuszMaciejewski** [comment]
The issue has been fixed and delivered to the develop branch.
