### ISSUE TITLE
Unable to resolve the source file for 'adminhtml/Magento/backend/en_GB/menuNodes.js' [] []

### ISSUE THREAD

**Issue by norgeindian** [SnowdogApps/magento2-menu#231]
When using another language than `en_US`, the node section loads forever and displays nothing:
![Screenshot from 2022-01-21 15-56-36](https://user-images.githubusercontent.com/11156287/150549239-76591d36-9410-47b6-842a-bb881c5d8f1f.png)

**Comment by andrzejborkowski** [comment]
Thank you for reporting the issue! I've created an internal ticket DEV-86517, our dev team will check it soon and let you know

**Comment by norgeindian** [comment]
@andrzejborkowski , thanks for the fast reply. Could you already give me a short update regarding this issue?

**Comment by andrzejborkowski** [comment]
@norgeindian it's on our dev's list but we didn't check it yet, I'll let you know once we check/fix it and when changes will be released, but it can take some time

**Comment by andrzejborkowski** [comment]
@norgeindian hey, could you please provide your magento/menu module versions? Our dev checked with m2.4.3 and menu module 2.17.0 and we can't replicate the issue, so any additional details are appreciated. Thanks!

**Comment by norgeindian** [comment]
@andrzejborkowski, I had this issue now several times, even for `en_US`. It seems as if the code is not properly generated when being in developer mode without additional manual actions. I often switch between branches which include the module and ones, which don't. Then this is always a problem. Could you maybe give a hint, which actions need to be done when being in developer mode to make it work?

**Comment by andrzejborkowski** [comment]
we double-checked the issue you reported (in developer mode as well) and we still can't replicate it.
Could you please provide the steps and details about your environment (including magento and menu module versions) in order to replicate the issue? Thanks in advance!

**Comment by norgeindian** [comment]
@andrzejborkowski , thanks for coming back to me here.
We're using `magento/product-community-edition` in version `2.4.3-p1` and the menu module in version `2.18.0`
In general, we have a docker setup where we run the instance, but that should be unrelated.
Like I said, it happened only when switching branches between a branch which had the module included and one which did not.
After each switch, I just ran `composer install`and `setup:upgrade`, which should usually be enough.
Do I need to run another command, so that the files get properly generated in every case?

**Comment by andrzejborkowski** [comment]
@norgeindian hey, below is feedback from our developer, please take a look and let me know if you have any further questions.
>I created clean project, added snowdog menu module and it works ok for me.
> The issue occurs during checkout between branches so maybe there are some changes in vendor folder in menu module? They may not be displayed as changed files in main project so I would recommend clean & composer install again.a
> I'm also wondering if it's not working at all for them on specific branch or they're able to run it somehow.
>

**Comment by andrzejborkowski** [comment]
@norgeindian hey, any update on this? Can close this issue?

**Comment by norgeindian** [comment]
@andrzejborkowski , actually, I could not reproduce it anymore. So yeah, let's close it. Thanks for asking.
