### ISSUE TITLE
Editing a new node takes 4-5 minutes to open for big catalog

### ISSUE THREAD

**Issue by norgeindian** [SnowdogApps/magento2-menu#232]
In our shop we have about 30 k categories, 90 k products and 2 k CMS pages.
When I try to create a new menu node in the backend and want to open the node using the pencil, it takes about 4-5 minutes to open the node view, where I can actually enter details and choose the node type.
I assume, that this might be related to the preloading of all existent data.
Is there some workaround here, as the module is almost not usable this way?

**Comment by andrzejborkowski** [comment]
thanks for reporting the issue, I created a ticket for our dev team DEV-86518, we'll check it soon and let you know then

**Comment by norgeindian** [comment]
@andrzejborkowski , thanks for the fast reply. Could you already give me a short update regarding this issue?

**Comment by andrzejborkowski** [comment]
@norgeindian  it's on our dev's list but we didn't check it yet, I'll let you know once we check/fix it and when changes will be released, but it can take some time

**Comment by norgeindian** [comment]
@andrzejborkowski , I now actually found a way in creating dummy classes for the node blocks which return more or less nothing in all function, but in `getJsonConfig`:

```
public function getJsonConfig(): array
    {
        return [
            'snowMenuAutoCompleteField'      => [
                'options' => [],
            ],
            'snowMenuNodeCustomTemplates'    => [
                'options' => [],
            ],
            'snowMenuSubmenuCustomTemplates' => [
                'options' => [],
            ]
        ];
    }
```
This is not pretty, but works at least, and now the process is a lot faster.
Would be awesome, if you could find a way, so that an admin can decide, which node types he needs
