### ISSUE TITLE
Set the submenu and node templates based on the main template

### ISSUE THREAD

**Issue by Bartdegroot** [SnowdogApps/magento2-menu#233]
We are creating a few frontend menu templates (like simple, vertical and mega) so we can use these defaults in our projects based on the requirements of the customers. If we add a custom main menu in the default.xml like this:

```xml
<block class="Snowdog\Menu\Block\Menu" name="mainmenu_desktop_custom" as="mainmenu.desktop.custom">
    <arguments>
        <argument name="menu" xsi:type="string">main</argument>
    </arguments>
    <action method="setTemplate">
        <argument name="template" xsi:type="string">Snowdog_Menu::main/vertical/menu.phtml</argument>
    </action>
</block>
```

the main template is set to `Snowdog_Menu::main/vertical/menu.phtml` (as it should be). However the templates for `sub_menu.phtml` and the node_types aren't changed and still point to `Snowdog_Menu::menu/sub_menu.phtml` (or `Snowdog_Menu::main/menu/sub_menu.phtml` if you use the identifier). We would like to automatically set the templates for the sub_menu and node_types based on the main template for menu.phtml set in the XML. 

Are we doing something wrong? Or is this not possible at the moment? In the `public function getMenuTemplate` in the file `snowdog/module-menu/Model/TemplateResolver.php` there is a check for `$block->getCustomTemplate()`, but this function doesn't seem to exist. We don't know if this should change the templates for the sub_menu and node_types, or that it is a new functionality.

**Comment by Igloczek** [comment]
So, you would like to customize temples for a given menu ID, am I correct?

Did you check the docs already? https://github.com/SnowdogApps/magento2-menu/wiki/Overwriting-templates-per-menu-ID

**Comment by Igloczek** [comment]
We will send this to our backend developers to check, but it won't be fast, since this is more a feature request, than a bug. @andrzejborkowski can you handle that? The goal is to check if it's possible to get child node templates relative to the `menu.phtml` file location, that is customizable via XML.

Meanwhile, if you can prepare such changes on your own, please submit a PR, we will be happy to check it and then make it part of this module.

**Comment by kiber** [comment]
@Bartdegroot changes are in **feature/87135** branch. 
Now module allows setting **submenu** template via layout XML.
If you can, please also test it on your side and verify that it helps to solve your problem.

```
<block name="menu-main-desktop" class="Snowdog\Menu\Block\Menu">
    <arguments>
        <argument name="menu" xsi:type="string">main-desktop</argument>
        <argument name="subMenuTemplate" xsi:type="string">Vendor_Module::main/vertical/sub_menu.phtml</argument>
    </arguments>
</block>
```

**Comment by Bartdegroot** [comment]
Thank you very much! This indeed solves the problem!
