### ISSUE TITLE
Import from Categories not updating Vue App

### ISSUE THREAD

**Issue by michalbiarda** [SnowdogApps/magento2-menu#236]
Steps to reproduce:

1. Create new menu
2. Click "Import from Categories" button and confirm action
3. Wait for server to fetch the data

Result: Vue App is not updated with the results.
Expected result: Vue App is updated with the results.

**Comment by andrzejborkowski** [comment]
@michalbiarda thanks for the PR, we appreciate it! I created an internal ticket and our devs will review it soon.
