### ISSUE TITLE
Provide store filter for CMS pages and CMS blocks / possibility to filter manually

### ISSUE THREAD

**Issue by norgeindian** [SnowdogApps/magento2-menu#238]
We have a shop with a lot of different stores and CMS content.
This way, the dropdown for choosing a CMS block in a CMS block node gets really really big and it's almost impossible to find the wanted entity.
As the store is selected above, it would be awesome, if this list could be filtered by the given store automatically.
Alternatively, it would be great, if one could filter manually by the title of the entity. Currently, I can actually enter text, but that does not filter anything and I can not select anything in the list.

**Comment by andrzejborkowski** [comment]
thanks for reporting the issue, but it appears that filtering already works as you described (filter by CMS block title) with the latest 2.18.0 module tag (see attached screen). Could you please check and confirm it works as expected?
![Screenshot 2022-03-28 at 17 33 03](https://user-images.githubusercontent.com/73829518/160434878-d7fcc40a-457b-482f-9796-688c86d1e9fe.png)

**Comment by norgeindian** [comment]
@andrzejborkowski , then the naming filter seems to be related to our data. I just saw in the dev tools, that we have the following error:  `Duplicate keys detected: '{"label":"XXX","store":["Deutsch"],"value":"YYY"}'. This may cause an update error.`
Might it be, that the filtering gets an issue as soon as the same value is twice inside the dropdown?
As the identifiers are only unique inside each store, this can happen in general.
So please be so kind, create two stores and include two blocks with the same identifier, but different names. Are you still able to filter? And you're surely with me, that currently no store filter is active, right? This would be a huge improvement.

**Comment by andrzejborkowski** [comment]
I checked the issue with multistores and can't replicate the issue even with the same CMS block identifiers. As you can see on the attached screen, I can look for the needed CMS block without any problem. And I don't think that store filter is needed here as you can see store assigned for each CMS block in dropdown. Let me know if you have any more questions. Thanks!
![Screenshot 2022-04-07 at 08 17 58](https://user-images.githubusercontent.com/73829518/162133810-33da2e2c-1ac3-43d3-9306-1e9c3ec5b8ec.png)
![Screenshot 2022-04-07 at 08 21 02](https://user-images.githubusercontent.com/73829518/162133812-3355875c-c9c2-4d5e-a754-6428110c26be.png)

**Comment by norgeindian** [comment]
@andrzejborkowski , okay, then I really don't get, why it does not work in my case...
Just to be sure: In your case not only the names, but also the identifier were the same?

Like I wrote in the beginning, we have about 2000 CMS blocks and a similar amount of CMS pages.
With the non-working search, it's almost impossible to choose the correct entity. This would be easier, if a store filter would be active. But I agree, as soon as the search works, this would indeed not be needed.
I will debug into that and let you know as soon as I understood more detailed, what goes wrong here

**Comment by andrzejborkowski** [comment]
yes, I used the same identifiers for CMS pages/blocks (you can see it on the second screen in the previous note)
