### ISSUE TITLE
Expected CSS

### ISSUE THREAD

**Issue by James-Moon-Audio** [SnowdogApps/magento2-menu#24]
I've attempted to use the extension, but it does not display properly.  I'm thinking it's due to the theme being used.

What CSS does this extension expect to have it display properly?

**Comment by Igloczek** [comment]
We are not shipping any CSS, b/c it's a tool for building custom menus, so at all, we expect that the CSS will be custom too. In the close future we are not going to change it, probably we will even remove more, like JS files, to just render a bunch of HTML code.

In the future we will release [an open source theme](https://github.com/SnowdogApps/magento2-alpaca-theme) which uses this module, so it will be styled and ready to use out of the box.

**Comment by rav-redchamps** [comment]
@James-Moon-Audio  If you are looking for support on Luma or Luma based themes then you may try this https://github.com/redchamps/snowdog-menu-luma-support we added Luma classes to the menu

**Comment by vseager** [comment]
@James-Moon-Audio An alternative for Luma https://github.com/vseager/magento2-snowdog-menu-luma

**Comment by Igloczek** [comment]
@vseager can you say a word or two about your module? Is that a fork of the previous one from RedChamps with some updates or something completely new?

**Comment by vseager** [comment]
@Igloczek No, this module is completely new and built from scratch. Unlike the RedChamps module which tried to replicate the template and classes of Luma, my module doesn't attempt to replicate any core templates and uses all core logic.

The only difference between my module and core Magento is that the core builds the menu nodes from the category structure. I am instead I am pulling out nodes from the SnowDog menu, and building the menu that way. This is all backend logic before it hits the frontend. As a result, my module works flawlessly with Luma and the Magento core, and should Magento update Luma templates/CSS/JS, then it won't have any negative effect, as this module doesn't involve any frontend involvement at all.

**Comment by Igloczek** [comment]
Nice! I'll put your module on the list in the [README.md](https://github.com/SnowdogApps/magento2-menu/blob/develop/README.md)
