### ISSUE TITLE
Node type "Category Child" do not work

### ISSUE THREAD

**Issue by chaikivskyi** [SnowdogApps/magento2-menu#246]
### Steps to reproduce
1. Enable `Flat Catalog Category` option (Stores > Configuration > Catalog > Storefront > Flat Catalog Category)
2. Create menu with node type `Category Child`

### Expected result
Menu will show all children categories

### Actual result
No one child category is displayed

**Comment by aborkowskiy** [comment]
Since "Flat Catalog" is not recommended anymore for magento versions  ≥ 2.4 we wouldn't handle this request, sorry.
