### ISSUE TITLE
Dublicate do not work correctly

### ISSUE THREAD

**Issue by chaikivskyi** [SnowdogApps/magento2-menu#247]
### How to reproduce
1. Create a menu
2. Add two nodes (or more)
3. Move the oldest node as a child of the newest
4. Click duplicate menu

### Expected result
All nodes of the menu will be duplicated

### Actual result
Child nodes were not created for nodes where the parent id is less than the id of child nodes

**Comment by chaikivskyi** [comment]
https://github.com/SnowdogApps/magento2-menu/pull/248

**Comment by chaikivskyi** [comment]
> Hi @chaikivskyi, thank you for reporting the issue. I was trying to replicate it with the latest menu module version (2.19.0) and magento m2.4.2 and for me menu duplicating works as expected (attaching screen of parent/child nodes in duplicated menu). Could you please try the latest menu tag and check if the issue persists there as well? ![Screenshot 2022-06-22 at 16 10 56](https://user-images.githubusercontent.com/38654362/175050719-b2c16a48-65bd-4da1-96cb-de5f6094ac71.png)

Yes, I replicated this issue on the latest version of the module. Can you move node 2 as the child of node 3 and try again?

**Comment by andrzejborkowski** [comment]
Thank you for provided steps, now I was able to reproduce the issue. I created an internal ticket DEV-90908, we'll check your PR soon

**Comment by adamwaclawczyk** [comment]
PR was merged, closing this issue
