### ISSUE TITLE
Module not working on 2.2 EE

### ISSUE THREAD

**Issue by mmmaxxx** [SnowdogApps/magento2-menu#25]
I get the following errors when trying to create a new menu in Magento 2.2 EE:

```
Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'v.entity_id' in 'on clause', query was: SELECT `e`.`entity_id`, `e`.`parent_id`, `v`.`value` AS `name` FROM `catalog_category_entity` AS `e`
 INNER JOIN `catalog_category_entity_varchar` AS `v` ON v.entity_id = e.entity_id AND v.store_id = 0 
            AND v.attribute_id = 45 WHERE (e.level > 0) AND (e.created_in <= 1) AND (e.updated_in > 1) ORDER BY `e`.`level` ASC, `e`.`position` ASC

Exception #1 (PDOException): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'v.entity_id' in 'on clause'

Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'v.entity_id' in 'on clause', query was: SELECT `e`.`entity_id`, `e`.`parent_id`, `v`.`value` AS `name` FROM `catalog_category_entity` AS `e`
 INNER JOIN `catalog_category_entity_varchar` AS `v` ON v.entity_id = e.entity_id AND v.store_id = 0 
            AND v.attribute_id = 45 WHERE (e.level > 0) AND (e.created_in <= 1) AND (e.updated_in > 1) ORDER BY `e`.`level` ASC, `e`.`position` ASC
```

Is this due to catalog_category_entity_varchar. entity_id being replaced by row_id in EE?

**Comment by DariuszMaciejewski** [comment]
@mmmaxxx  thank you for your report.

**Comment by DariuszMaciejewski** [comment]
@mmmaxxx I can't reproduce this error on Magento EE 2.2.1 with the current stable module version (v2.1.0).
Please check the module version you have.

**Comment by mmmaxxx** [comment]
@DariuszMaciejewski I just tried with version 2.2.1 and its working fine now.

**Comment by DariuszMaciejewski** [comment]
@mmmaxxx okay. thanks for the feedback.

**Comment by realchriswells** [comment]
I started suffering this too using version 2.2.1. I upgraded to 2.3.0 and still got it.

I managed to fix it by changing the database values for the node `type` from `cms_page` to `custom_url`, however I can't get in to the menu settings either (I've submitted a separate ticket relating to this, issue #42 )
