### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'identifier' in 'snowmenu_menu'

### ISSUE THREAD

**Issue by Aquive** [SnowdogApps/magento2-menu#250]
Hi, 

I pulled package with composer, now I am running `bin/magento setup:upgrade`, I get the following error. This is first time installing it.

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'identifier' in 'snowmenu_menu'` 

Magento version: 2.4.2
snowdog/module-menu version: 2.19.0

**Comment by adamwaclawczyk** [comment]
I couldn't reproduce this on a fresh Magento 2.4.2 instance.

Please try the steps listed below:

1. Backup DB
2. Drop `snowmenu_node`, `snowmenu_node`, `snowmenu_store` tables
3. Delete entry from setup_module with `DELETE from setup_module WHERE module LIKE "Snowdog_Menu";`
4. Try running `bin/magento setup:upgrade` again

We're happy to help with any further problems 😃

**Comment by Aquive** [comment]
@adamwaclawczyk this worked. Thanks for the support!

**Comment by james-windandkite** [comment]
For anyone who gets this issue now. if you pull the latest version, I've rolled out a fix for this here.

You can pull it like this: `composer require hyva-themes/magento2-snowdog-menu:0.1.0`

Resolved here:
https://gitlab.hyva.io/hyva-themes/hyva-compat/magento2-snowdog-menu/-/commit/ee9a7724e838e32b1282ae7501bb45ee5db66dac
