### ISSUE TITLE
Deployment issue with compact strategy

### ISSUE THREAD

**Issue by vahir2016** [SnowdogApps/magento2-menu#251]
Hello,

I have got an issue with your module : it works on my dev environnement but when it came to integration, vue files are missing.

It's an issue that I have only with "compact" strategy deployment for statics files (it works with quick strategy). 

`se:st:de -f --strategy compact`

Sadly, I don't have the choice to use compact strategy (infra guys doesn't allow to switch). 

I don't know how to fix my problem, maybe have you got a clue ? Is it working on your side with compact strategy deployment ?

Thank you.

**Comment by andrzejborkowski** [comment]
Hi, we created an internal ticket DEV-93269, once our dev team checks it I'll let you know. Have a great day!

**Comment by vahir2016** [comment]
Ok thank you. I reproduced the issue on my dev environnement but I had to switch magento to production mode and deploy with compact strategy.

**Comment by vahir2016** [comment]
Hello Adam,

Thank you, I will try it as soon as possible, I solved my issue with a hard (uggly) fix in requirejs-config.js

**Comment by andrzejborkowski** [comment]
hi @vahir2016 , I'm closing this issue, but please feel free to re-open it or add a new one in case of troubles. Have a great day!
