### ISSUE TITLE
How to show/hide category on menu with respect to Catalog Permission feature of Adobe commerce?

### ISSUE THREAD

**Issue by RakeshJesadiya** [SnowdogApps/magento2-menu#254]
I have just installed Snowdog Menu in one of my Adobe commerce sites.
Clients use the box Catalog Permission feature for their B2B site. Is there any feature to show/hide categories based on the customer group on the snowdog menu?

Currently, this feature is not working for the B2B site with the snowdog menu.

How to accomplish the snowdog menu with the Catalog permission feature based on the customer group of the customer in Magento 2?

Thank you.

**Comment by andrzejborkowski** [comment]
Hi @RakeshJesadiya 
we checked the issue with the dev team and think that we can add an optional field with multi selector type to allow admins to select multiple customer groups or leave it empty (so there's no customer groups restriction). I've created an internal ticket DEV-94738, but since it's a pretty complicated feature it could take us 2-4 months to implement, once it's ready we'll include it to the release. 
Regards,
Andrzej

**Comment by RakeshJesadiya** [comment]
@andrzejborkowski This is good feature request for the Magento B2B site, if we are using the snowdog menu with B2B site, snowdog menu will be useless because of the category restriction is not working with it.

**Comment by rohan-navigate** [comment]
> Hi @RakeshJesadiya we checked the issue with the dev team and think that we can add an optional field with multi selector type to allow admins to select multiple customer groups or leave it empty (so there's no customer groups restriction). I've created an internal ticket DEV-94738, but since it's a pretty complicated feature it could take us 2-4 months to implement, once it's ready we'll include it to the release. Regards, Andrzej

@andrzejborkowski, I am curious to know if this feature has been developed. I have the same requirement and was thinking about using this module to show/hide the menu based on the catalog permission.

**Comment by andrzejborkowski** [comment]
Hi @rohan-navigate,
it's still in development, but we are close to releasing it soon. However, I'm unable to provide an exact deadline for its completion at this moment.

**Comment by rohan-navigate** [comment]
> Hi @rohan-navigate, it's still in development, but we are close to releasing it soon. However, I'm unable to provide an exact deadline for its completion at this moment.

@andrzejborkowski Thanks for your response. My team was soon going to custom-develop this feature. But we can hold off until we hear from you.

**Comment by AlbertLeatt** [comment]
Glad I found this, we'd also like to have this feature for our Magento Commerce site.
@andrzejborkowski please keep us posted, thanks!

**Comment by andrzejborkowski** [comment]
This has been released already in 2.27.0 menu module version https://github.com/SnowdogApps/magento2-menu/blob/2.27.0/CHANGELOG.md
