### ISSUE TITLE
Menu not visible when category isn't found

### ISSUE THREAD

**Issue by mikesteeghs** [SnowdogApps/magento2-menu#255]
Set up the menu with a menu-item with Node Type **Category**, and choose an exsisting category. After saving, the menu (with category link) will be visible. Now remove the category that you've used in the menu. The complete menu has now disappeared.

Isn't it possible to still show the menu but not render the concerning menu-item?

**Comment by andrzejborkowski** [comment]
hi @mikesteeghs 
I was trying to replicate the issue following the steps you've provided and using magento 2.4.2 + menu module 2.20.0 but I see that after removing the category I've previously set in Category menu node, only Category path has been removed in node settings but not the whole menu (see attached screens). Could you please pull the latest menu module version and try again?
Regards, 
Andrzej

![1 adding menu with Category node](https://user-images.githubusercontent.com/73829518/200542583-9fdf98fc-4fc8-48a6-ae90-f09e768d0b97.png)
![2  removing selected category](https://user-images.githubusercontent.com/73829518/200542588-0e041b48-4446-4126-ac8b-d1f6ffc99306.png)
![3 category path got empty](https://user-images.githubusercontent.com/73829518/200542590-0cc6a664-aa02-4e91-8c76-4bbc14b7c072.png)

**Comment by andrzejborkowski** [comment]
Closing the ticket due to the lack of activity
