### ISSUE TITLE
Where to place new custom menu type vue file?

### ISSUE THREAD

**Issue by marvinhinz** [SnowdogApps/magento2-menu#260]
I see no sane way to add a custom menu type vue file, because in the VueProvider the COMPONENT_PATH is hardcoded and forces you to use a custom adminhtml theme, intercepting the vueprovider or moving the whole module from vendor to app/code.

Is there something i am missing?

**Comment by JKrupinski** [comment]
Every node has it's own Block e.g. `vendor/snowdog/module-menu/Block/NodeType/Wrapper.php`
it's added to `vendor/snowdog/module-menu/etc/di.xml`
```<item name="wrapper" xsi:type="object">Snowdog\Menu\Block\NodeType\Wrapper</item>```
```
<type name="Snowdog\Menu\Model\VueProvider">
        <arguments>
            <argument name="components" xsi:type="array">
                <item name="category" xsi:type="string">category</item>
                <item name="product" xsi:type="string">product</item>
                <item name="cms_page" xsi:type="string">cms-page</item>
                <item name="cms_block" xsi:type="string">cms-block</item>
                <item name="custom_url" xsi:type="string">custom-url</item>
                <item name="category_child" xsi:type="string">category-child</item>
                <item name="wrapper" xsi:type="string">wrapper</item>
            </argument>
        </arguments>
    </type>
```

there's also `wrapper.phtml` template
`vendor/snowdog/module-menu/view/frontend/templates/menu/node_type/wrapper.phtml` 
and `wrapper.vue`
`vendor/snowdog/module-menu/view/adminhtml/web/vue/menu-type/wrapper.vue`

`const COMPONENT_PATH = 'vue!Snowdog_Menu/vue/menu-type/%s';`

it's not hardcoded, there's `$data[] = sprintf(self::COMPONENT_PATH, $component);` which replaces `%s` with component path

**Comment by andrzejborkowski** [comment]
@marvinhinz can we close the issue now?

**Comment by andrzejborkowski** [comment]
closing this issue due to the lack of activity
