### ISSUE TITLE
{{store url=""}} fails to render in Custom URL node types

### ISSUE THREAD

**Issue by atIOCrON** [SnowdogApps/magento2-menu#261]
**STEPS TO REPRODUCE**

1. Content > Elements: Menus
2. Edit an existing menu or create a new menu
3. Create a new node
   1. Enabled: Yes
   2. Node Type: Custom URL
   3. Custom URL: {{store url="example"}}
4. Click Save
5. Clear the Magento cache
6. Browse to a frontend page that contains the menu

**EXPECTED RESULT**

`{{store url="example"}}` renders as the full store URL, e.g. [https://www.example.com/example/](https://www.example.com/example/ "‌")

**ACTUAL RESULT**

`{{store url="example"}}` fails to render. It shows as `{{store url="example"}}` in the HTML source code.

**Comment by andrzejborkowski** [comment]
@atIOCrON any update on this?

**Comment by andrzejborkowski** [comment]
closing this ticket due to the lack of activity
