### ISSUE TITLE
Category not loading properly and showing JS error in console

### ISSUE THREAD

**Issue by skanungo1** [SnowdogApps/magento2-menu#262]
Hi Team,

I am facing an issue related to the menu node when I select "Node Type : Category" and then went to select the "Category" it shows me loading option as given in the below screenshot. I also found error in console which also mentioned.

![Screenshot from 2023-02-22 19-12-40](https://user-images.githubusercontent.com/87975097/220641679-0170792f-6dab-4973-b06f-93dd925452e3.png)

Please check this and suggest us the feasible solution or the problem why this issue arrived.

Magento ver: 2.4.5-p1
Snow_Menu module ver: 2.20.0

Thanks,

**Comment by andrzejborkowski** [comment]
Hi @skanungo1 
thanks for reporting this issue, I think it could be due to the incompatibility of our menu module with m2.4.5, but our dev team will check and confirm it soon. The latest magento version we have tested our menu module with is 2.4.4-p2.
Regards,
Andrzej

**Comment by skanungo1** [comment]
Hi @andrzejborkowski 

Following up on the issue. Can you please let us know if this issue is reproducible at your end and what solution will to preferred for this.

Thanks,

**Comment by andrzejborkowski** [comment]
Hi @skanungo1 
we tested menu module ver.2.20.0 and Magento 2.4.5-p1 and we didn't spot such issue. Below is feedback from our backend dev:

> I debugged for what happens if vue app does not get(or gets faulty) categories data, the vue component renders a note "No options available." so I don't think it's a problem with how we're loading categories data but instead something related to vue itself(what's weird is that some categories are loaded, there still is a chance something's wrong with their categories or with how we're processing them - still, not enough info to tell that)


We are still waiting for our frontend dev feedback. I'll keep you posted.

Regards,

**Comment by andrzejborkowski** [comment]
hi @skanungo1 , please take a look at the following note from our fronend dev and let me know if this resolved the issue you have:

> Please override this template: *vendor/snowdog/module-menu/view/adminhtml/templates/menu/nodes.phtml*
> and change *"lazyMinItemsCount": "1000",* to a bigger number e.g 2000 or more (test different limits) until  *vendor/snowdog/module-menu/view/adminhtml/web/vue/field-type/autocomplete.vue* template is loaded instead of *autocomplete-lazy.vue*
> 
> I guess there's a something wrong with *.children* property in *loadOptions* method in this file *vendor/snowdog/module-menu/view/adminhtml/web/vue/field-type/autocomplete-lazy.vue*
> 
> Please test solution above and if it won't help I'll investigate it more

Thanks

**Comment by andrzejborkowski** [comment]
closing the ticket due to a lack of activity
