### ISSUE TITLE
2.4.6 and PHP 8.2 compatibility

### ISSUE THREAD

**Issue by 101Luuk** [SnowdogApps/magento2-menu#269]
Hi,

When i upgrade Magento to 2.4.6 and PHP to 8.2 i got the following errors:

<b>Deprecated</b>:  Using ${var} in strings is deprecated, use {$var} instead in <b>./vendor/snowdog/module-menu/Block/Menu.php</b> on line <b>417</b><br />

Exception #0 (Exception): Deprecated Functionality: Creation of dynamic property Snowdog\Menu\Model\Menu\NodeRepository::$searchResultsFactory is deprecated in ./vendor/snowdog/module-menu/Model/Menu/NodeRepository.php on line 38

**Comment by andrzejborkowski** [comment]
Hi @101Luuk 

thanks for reporting this issue, it has been fixed already within this PR https://github.com/SnowdogApps/magento2-menu/pull/265 and merged to develop branch already. We'll add these changes to the next release soon.

Regards,
Andrzej

**Comment by iranimij** [comment]
When do you release this PR ?
