### ISSUE TITLE
Ability to overwrite all templates per menu ID

### ISSUE THREAD

**Issue by Igloczek** [SnowdogApps/magento2-menu#27]
It might work same way as in the Banana module for M1, where we can add menu ID to the name of the template
![](https://i.imgur.com/nGO3TYI.png)

Even better will be to base it on folders i.e for ID `menu-mobile` we would like to overwrite templates as `/Snowdog_Menu/templates/menu-mobile/menu.phtml` and `/Snowdog_Menu/templates/menu-mobile/menu/node_type/category.phtml`

**Comment by DariuszMaciejewski** [comment]
Internal ticket DEV-36174
