### ISSUE TITLE
Can't open menu grid in admin panel after installation

### ISSUE THREAD

**Issue by maciejmakson** [SnowdogApps/magento2-menu#277]
I am facing an issue with the snowdog/module-menu extension in the admin panel of my Magento installation. After installation I have 404 error when I try to enter: `Admin panel -> Content -> Menus` (when I have disabled secret key in url). When secret key is enabled I have exception "Invalid security or form key. Please refresh the page".

I have tried for versions 2.20, 2.21 - the issue is the same for both. Magento version: 2.4.5-p2

**Comment by andrzejborkowski** [comment]
Hi @maciejmakson, 
thanks for reporting the issue. I created an internal ticket DEV-100321 in order to check this issue. We'll be back with reply soon.
Regards,
Andrzej

**Comment by jochhop** [comment]
Hi @maciejmakson thanks for reporting the issue, however, we cannot replicate it. We have tested it with version 2.21 and a vanilla Magento 2.4.5-p2 version. The tests were executed with:

- Url secret key enabled
- Url secret key disabled

Both ways worked correctly (see attached screenshots)

<img width="1502" alt="snow_menu_245p2_test_security_key_enabled" src="https://github.com/SnowdogApps/magento2-menu/assets/5047013/15480013-503e-49e4-aa68-2119fa55c830">
<img width="1503" alt="snow_menu_245p2_test_url_security_key_disabled" src="https://github.com/SnowdogApps/magento2-menu/assets/5047013/9f471c19-eab7-42db-b663-eec801a42294">

Do you have more information about how do you replicate the issue? Is it a vanilla Magento installation?

Thanks in advance

**Comment by maciejmakson** [comment]
I resolved issue on my own. It was server issue related to certain project. I was unable to reproduce this error on local env. It was only for stage environment.

Thank you for your time.

**Comment by jochhop** [comment]
Thank you for the information! @maciejmakson have a great day!
