### ISSUE TITLE
.vue files are not loaded accordingly on admin when compact compile is enabled

### ISSUE THREAD

**Issue by andrewdaluz** [SnowdogApps/magento2-menu#284]
On Adobe Cloud we have the ability to enable the compact mode for disk space-saving, this will generate the main inheritance template files from `default` and `base`, and the languages are not required or included in the static files generation.
```
stage:
  build:
    SKIP_SCD: false
    SCD_STRATEGY: "compact"
```

This is causing the admin menu edit page to break as `.vue` files are not loaded/found.

To replicate this issue you can enable production mode and run the compact mode (you must clean up static folders), as like:
```
bin/magento setup:static-content:deploy en_US -s compact
```

**Comment by andrewdaluz** [comment]
I don't know if there is any way of fixing it by SnowdogApps module but the fix is basically:

When the static content is ran the following file verify the files extension mapping just for .html  and .js to replace the inheritance to use default template instead of specific language package.
```
vendor/magento/module-deploy/Package/Processor/PostProcessor/Map.php
foreach ($map as $fileId => $fileInfo) {
            if (!in_array(pathinfo($fileId, PATHINFO_EXTENSION), ['js', 'html'])) {
                continue;
            }

            $fileId = '/' . $fileId; // add leading slash to match exclude patterns
            $filePath = $this->minification->addMinifiedSign(str_replace(Repository::FILE_ID_SEPARATOR, '/', $fileId));
            $filePath = substr($filePath, 1); // and remove
            $jsonMap[$filePath] = '../../../../'
                . $fileInfo['area'] . '/' . $fileInfo['theme'] . '/' . $fileInfo['locale'] . '/';
        }
```
The problem I had was with a custom module that requires .vue js files.
So adding the vue into the array did the trick.

```
diff --git a/Package/Processor/PostProcessor/Map.php b/Package/Processor/PostProcessor/Map.php
index 97b5731..9eac6ef 100644
--- a/Package/Processor/PostProcessor/Map.php
+++ b/Package/Processor/PostProcessor/Map.php
@@ -139,7 +139,7 @@
     {
         $jsonMap = [];
         foreach ($map as $fileId => $fileInfo) {
-            if (!in_array(pathinfo($fileId, PATHINFO_EXTENSION), ['js', 'html'])) {
+            if (!in_array(pathinfo($fileId, PATHINFO_EXTENSION), ['js', 'html', 'vue'])) {
                 continue;
             }
 

```

**Comment by adamwaclawczyk** [comment]
Thanks for providing your findings.

FYI This issue was previously resolved by providing a requirejs workaround for loading vue files in #251

Closing this issue since it looks like everything's resolved
