### ISSUE TITLE
Missing closing } in cms_page.phtml

### ISSUE THREAD

**Issue by ThomasNegeli** [SnowdogApps/magento2-menu#288]
https://github.com/SnowdogApps/magento2-menu/blob/e3795a05e299a4a37fb87ca58dfaa50b8916b84f/view/frontend/templates/menu/node_type/cms_page.phtml#L19

There is a closing } missing.

**Comment by adamwaclawczyk** [comment]
Fixed in 2.23.1 with 312fe917b44734c10049393ab9b62e2af700131a
