### ISSUE TITLE
Menu Block has active_node_id data but it seems not usable with caching

### ISSUE THREAD

**Issue by bscthartmann** [SnowdogApps/magento2-menu#296]
With \Snowdog\Menu\Block\Menu there is the data property "active_node_id". I figured out that this data is not correct while having cache activated and also I have seen the module marks the "current" navigation item with the help of JavaScript.

Is this an expected behavior, does JS has to be used to determine the "current/active" navigation item?

**Comment by adamwaclawczyk** [comment]
Could you link to in-code reference to `active_node_id`?

There were some changes to current/active behavior, maybe this will help clear some things up: https://github.com/SnowdogApps/magento2-menu/issues/276#issuecomment-1628230149

**Comment by adamwaclawczyk** [comment]
Closing, feel free to reopen
