### ISSUE TITLE
Uncaught TypeError: tree.get_json is not a function

### ISSUE THREAD

**Issue by SilvanLaroo** [SnowdogApps/magento2-menu#30]
Hi,

If we're trying to add/remove a node in the backend we get this js error: `Uncaught TypeError: tree.get_json is not a function`.

Steps to reproduce
--
1. Install Module Menu version 2.1.0 (in this case on Magento 2.1.7)
2. Open the 'Create new menu' page
3. Select 'Nodes tab'

Expected result
--
1. The option to create / add a node

Actual result
--
1. No option to add node
2. JS error thrown, see: https://www.dropbox.com/s/oj4dpe9jpwvh7k1/Schermafbeelding%202017-12-08%20om%2009.55.29.png?dl=0

**Comment by Igloczek** [comment]
@talalus could you take a look at this?

**Comment by SilvanLaroo** [comment]
Could you give an update regarding this issue?

**Comment by Igloczek** [comment]
I created internal ticket [DEV-37608] to schedule fixing this bug.

**Comment by talalus** [comment]
I couldn't reproduce this issue, @SilvanLaroo may you check if Snowdog_Menu/js/jstree.js is loaded

**Comment by SilvanLaroo** [comment]
@talalus yes I can see that jstree.js is loaded.

**Comment by SilvanLaroo** [comment]
Just tried a fresh install of Magento 2.1.11 with this extension, I still get the error.

**Comment by talalus** [comment]
@Igloczek  I think we can close this because a complete rewrite for the admin will be done in #21 using VueJS and jstree will be removed

**Comment by Igloczek** [comment]
Rewritten admin area will be released in version 2.5.0
