### ISSUE TITLE
Adding new types of nodes does not register the new element

### ISSUE THREAD

**Issue by ebaraut** [SnowdogApps/magento2-menu#301]
When adding a new type node, vue.js looks for the element in `const COMPONENT_PATH = 'vue!Snowdog_Menu/vue/menu-type/%s';`

This code in di.xml
```
    <type name="Snowdog\Menu\Model\NodeTypeProvider">
        <arguments>
            <argument name="providers" xsi:type="array">
                <item name="row_wrapper" xsi:type="object">Vendor\SnowdogMenu\Block\NodeType\RowWrapper</item>
            </argument>
        </arguments>
    </type>
    <type name="Snowdog\Menu\Model\VueProvider">
        <arguments>
            <argument name="components" xsi:type="array">
                <item name="row_wrapper" xsi:type="string">row-wrapper</item>
            </argument>
        </arguments>
    </type>
```
throws this error: `https://my.site/static/adminhtml/Magento/backend/en_US/Snowdog_Menu/vue/menu-type/row-wrapper.vue 403 (Forbidden)`

And this code in di.xml
```
<type name="Snowdog\Menu\Model\NodeTypeProvider">
        <arguments>
            <argument name="providers" xsi:type="array">
                <item name="row_wrapper" xsi:type="object">Vendor\SnowdogMenu\Block\NodeType\RowWrapper</item>
            </argument>
        </arguments>
    </type>
    <type name="Snowdog\Menu\Model\VueProvider">
        <arguments>
            <argument name="components" xsi:type="array">
                <item name="row_wrapper" xsi:type="string">Vendor_SnowdogMenu::vue/menu-type/row-wrapper</item>
            </argument>
        </arguments>
    </type>
```
throws this error: `[Vue warn]: Unknown custom element: <row_wrapper> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

**Comment by adamwaclawczyk** [comment]
Related #69 and #260
Since the vue component is declared outside of Snowdog_Menu, its path won't be passed down(VueProvider currently expects only Snowdog_Menu declared vue components).

First linked issue has some clues how to proceed.
I did a quick fix for this inside https://github.com/SnowdogApps/magento2-menu/blob/2f91df7e27bee4b45a48ee0df981d47be0dc3377/Model/VueProvider.php#L28

by adding to the `$data` array:
```php
$data[] = 'vue!Vendor_SnowdogMenu/vue/menu-type/row_wrapper';
```

**Comment by andrzejborkowski** [comment]
hi @ebaraut were you able to resolve your issue with the recommendation provided in the previous note? If so, we'd like to close this issue. Thanks!

**Comment by andrzejborkowski** [comment]
closing the issue due to the lack of activity
