### ISSUE TITLE
how to call it in frontend?

### ISSUE THREAD

**Issue by akies1** [SnowdogApps/magento2-menu#314]
Hi, can you share how to show the menu in the front end in the custom theme?

**Comment by andrzejborkowski** [comment]
Hi @akies1,
our menu module works out-of-the-box only with default Hyva theme, if you need to display menu in your custom theme you need to custmize your templates and add your own styles to fit your project needs. You can find more info about customizations on Wiki page here https://github.com/SnowdogApps/magento2-menu/wiki/Overriding-templates
