### ISSUE TITLE
Mobile menu not working in combination with the Hyvä stacked header

### ISSUE THREAD

**Issue by magex55** [SnowdogApps/magento2-menu#320]
Added a menu with identifier hyva-topmenu-mobile, cleared cache and reloaded the frontend. Nothing is shown on mobile devices. Menu is shown as soon as I switch back to desktop view.

How to fix?

**Comment by andrzejborkowski** [comment]
hi @magex55,
Thanks for reporting the issue. I think we can close it since the fix provided in https://github.com/SnowdogApps/magento2-menu/issues/306#issuecomment-2051123389 resolved the issue. We'll include those changes to the next menu module release once they are ready.
