### ISSUE TITLE
Only default category possible in "Import from categories" feature

### ISSUE THREAD

**Issue by magex55** [SnowdogApps/magento2-menu#326]
When I click the "Import from categories" button, I get to choose the category, but it only shows the default category and its sub categories. I have got a category parallel to the default category which I want to create the menu from. Possible?

**Comment by chrisastley** [comment]
Hi @magex55 , 

I added a commit not long back which was merged to fix this issue #318 

Check you have the most recent version installed.

**Comment by magex55** [comment]
Ok, that solved it, thanks

**Comment by andrzejborkowski** [comment]
hey @chrisastley, thanks for your feedback, I appreciate it! Closing the issue
