### ISSUE TITLE
Missing @return annotation for getCustomerGroups()

### ISSUE THREAD

**Issue by chrisastley** [SnowdogApps/magento2-menu#332]
An issue was introduced in the latest version preventing me from loading Swagger, not sure if the problem causes any other issues.

Method's return type must be specified using @return annotation. See Snowdog\Menu\Api\Data\NodeInterface::getCustomerGroups()

**Comment by chrisastley** [comment]
I've added a pull request #333 but please check it is the correct return, it does solve the issue I have though.

**Comment by andrzejborkowski** [comment]
Thank you for reporting the issue, I've created an internal ticket DEV-106800 and our dev team will review your PR soon

**Comment by adamwaclawczyk** [comment]
Thanks for spotting this so fast @chrisastley :)
I can imagine this was a real pain to find
`2.27.1` should be available now with this fix
