### ISSUE TITLE
Add foreign keys to tables

### ISSUE THREAD

**Issue by Koc** [SnowdogApps/magento2-menu#34]
Adding FK prevents database from collisions

- snowmenu_node.menu_id
- snowmenu_node.parent_id
- snowmenu_store.menu_id
- snowmenu_store.store_id
- snowmenu_node.content (maybe extract category_id, block_id, page_id as separate columns)

**Comment by DariuszMaciejewski** [comment]
Internal ticket DEV-37373

**Comment by DariuszMaciejewski** [comment]
@Koc thank you for reporting this issue!

**Comment by DariuszMaciejewski** [comment]
The changes will be available with the upcoming release.
Related commit: https://github.com/SnowdogApps/magento2-menu/commit/f915526750299d8e02808dc9ca8ee36456940064
