### ISSUE TITLE
Database issue after installing module

### ISSUE THREAD

**Issue by TheFrakes** [SnowdogApps/magento2-menu#342]
Hi,
I installed your module via composer (snowdog/modul-menu 2.27.1). Then, after I launched setup:upgrade, I got the following warning which lead to shutting down my whole shop:

```
Column definition "menu_id" and reference column definition "menu_id" are different in tables "snowmenu_node" and "snowmenu_menu"
Column definition "store_id" and reference column definition "store_id" are different in tables "snowmenu_store" and "store"
```

I am using magento 2.3.7-p1

**Comment by andrzejborkowski** [comment]
Hi @TheFrakes we do not support m2.3.x versions, please upgrade to m2.4.x version and check then. Thanks!

**Comment by TheFrakes** [comment]
Thanks for the reply. You should metion the version > 2.4.x somewhere. Maybe you can add a requirements tab.

**Comment by andrzejborkowski** [comment]
yes, I've asked our dev team to add information about compatible versions. Thank you!
