### ISSUE TITLE
Mobile menu design inconsistency with Hyva theme

### ISSUE THREAD

**Issue by Kashyap1999** [SnowdogApps/magento2-menu#343]
Hello,

We noticed that the Snowdog Magento2 Menu module uses a toggle for displaying menus and sub-menus in the mobile view. However, the Hyva theme provides a sliding menu design.

**Screenshot-1** (Snowdog mobile menu)
![hyva-theme-menu](https://github.com/user-attachments/assets/a462bfa8-77fc-43cb-b0ba-bd6210f7add8)

**Screenshot-2** (hyva theme menu)
![snowdog-menu](https://github.com/user-attachments/assets/10290f56-aa10-4e60-b10d-8ada68c24a43)

**Question:** What was the reasoning behind choosing the toggle design for the mobile menu in this module and not adding it as an extra option, but still allow the default Hyva mobile menu layout?

Suppose there are no particular reasons for the toggle design. Would you like to add a new feature that allows users to choose between the toggle design and a sliding menu option similar to the Hyva theme?
We would be happy to create a pull request for this enhancement if you are interested.

**Comment by andrzejborkowski** [comment]
Hi @Kashyap1999 , 
thank you very much for the suggestion to create a PR. However, the frontend part of the menu module was developed for the Hyva theme primarily as a demo, we do not plan to support any theme modification, but you can modify your theme if needed.

Best regards,
Andrzej
