### ISSUE TITLE
$escaper phpdoc missing

### ISSUE THREAD

**Issue by jg-development** [SnowdogApps/magento2-menu#344]
for better ide autocomplete the $escaper variable should be declared

https://github.com/SnowdogApps/magento2-menu/blob/develop/view/frontend/templates/menu/node_type/category.phtml#L34

missing:
/** @var \Magento\Framework\Escaper $escaper */

**Comment by andrzejborkowski** [comment]
hello @jg-development I created an internal ticket SMM-24 and our dev team will check it soon

**Comment by adamwaclawczyk** [comment]
Closing per https://github.com/SnowdogApps/magento2-menu/commit/6c665dcbe9535f48f8d0085708fa43dd7604bea1 commit
