### ISSUE TITLE
Complete menu is destroyed after update

### ISSUE THREAD

**Issue by henkvalk** [SnowdogApps/magento2-menu#348]
Hi, the complete menu is destroyed after changing the menu.

```
Could not save Menu: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database.snowmenu_customer' doesn't exist, query was: DELETE FROM `snowmenu_customer` WHERE (node_id = '1367') 
```

This is because the **database prefix** is not added.

**Comment by adamwaclawczyk** [comment]
Please have a check with newer version: `2.27.2`
And feel free to reopen issue if there are still problems - thanks!

**Comment by henkvalk** [comment]
Problem still exist in latest version.

```
Could not save Menu: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database.snowmenu_customer' doesn't exist, query was: DELETE FROM `snowmenu_customer` WHERE (node_id = '1367') 
```

**Comment by henkvalk** [comment]
I don't have permissions to reopen the issue

**Comment by adamwaclawczyk** [comment]
Do you have any errors when running `bin/magento setup:upgrade`?
The error is happening because some table is not created properly, it should be created after running above command.

**Comment by henkvalk** [comment]
Thanks. It's working now
