### ISSUE TITLE
Cann't access node classes from template

### ISSUE THREAD

**Issue by Koc** [SnowdogApps/magento2-menu#36]
```phtml

<?php /** @var \Snowdog\Menu\Block\NodeType\Category $block */ ?>

$class = $block->getMenuClass();
```

I can call `getMenuClass` but there is no method `getNodeClasses`, so node css classes attribute looks like useless.

**Comment by DariuszMaciejewski** [comment]
Node classes are basically used in the `getMenuHtml()` method while building html list elements, but I don't see reasons to not include them in node templates too.

**Comment by Koc** [comment]
@DariuszMaciejewski yes, stiil useful. I've opened PR for fixing this issue. Merging it enough for me :)

**Comment by DariuszMaciejewski** [comment]
Changes have been delivered to the develop branch.
