### ISSUE TITLE
URL rewrite always uses entity_id rather than row_id

### ISSUE THREAD

**Issue by mattwellss** [SnowdogApps/magento2-menu#4]
First, I want to say thanks for building just the module I'd designed in my head a couple weeks ago. Now I only need to extend it where necessary! 🎉 

In [`Snowdog\Menu\Model\ResourceModel\NodeType\Category::fetchData`](https://github.com/SnowdogApps/magento2-menu/blob/2.0.3/Model/ResourceModel/NodeType/Category.php#L84), the variable `$eavColumnName` is used to determine from which column of `url_rewrite` to select/filter results. However, even with the EE-only staging module installed, `url_rewrite` continues to use `entity_id`.

It looks like the issue also exists for `Snowdog\Menu\Model\ResourceModel\NodeType\CmsPage::fetchData`. 

If I create a pull request including modifications to those two classes to use the known column `entity_id`, would that be an acceptable fix?

**Comment by dmaciej** [comment]
You're right. I don't see a column such us `row_id` in the `url_rewrite` table in the Enterprise edition.
Yes, please open a pull request.

**Comment by Igloczek** [comment]
Released as 2.0.4
