### ISSUE TITLE
Add product node

### ISSUE THREAD

**Issue by jahvi** [SnowdogApps/magento2-menu#46]
I'm wondering if it would be worth adding a "products" node? It seems like a common use case to be able to link to specific products in the menu.

In my case I've used this before to display "featured products" in the menu, so it wouldn't just show the name but maybe the product image and price as well.

I think it could work exactly like the category node but pull through the product list instead.

**Comment by Igloczek** [comment]
We need it for one of our projects too.

**Comment by jahvi** [comment]
I'll be happy to work on a PR if you guys think it's worth it.

**Comment by Igloczek** [comment]
Feel free, we will be hapy to merge your solution if pass our review.

**Comment by jahvi** [comment]
I've had some success with this on my own project however I still need to clean up some things before submitting a PR, quick question is there a reason why you are getting the product node data directly from the DB instead of using a collection?

Take for example the category node:
https://github.com/SnowdogApps/magento2-menu/blob/master/Model/ResourceModel/NodeType/Category.php#L44-L81

**Comment by dawiddczaja** [comment]
@jahvi You mean category node data ? We get this data that way because it's faster than by collection. 

We have almost done this functionality. I think it's will be ready at the end of the week

**Comment by jahvi** [comment]
Yeah I was assuming that would be the case, that sounds great I had to do
this for a project I'm working on but I'm not very proud of how it turned
out

**Comment by talalus** [comment]
Ready in 2.5.0 version
