### ISSUE TITLE
Add support attaching icons/photos to menu nodes

### ISSUE THREAD

**Issue by Koc** [SnowdogApps/magento2-menu#48]
It would be nice add possibility to attach some images to menu items. Css classes couldn't cover this. Example use case:

![default](https://user-images.githubusercontent.com/191082/37083474-4a6073e2-21f8-11e8-803f-b1a822d509aa.png)

**Comment by Igloczek** [comment]
You can use CMS blocks for that. We don't want to duplicate the core features.
