### ISSUE TITLE
Product node adjustment

### ISSUE THREAD

**Issue by bartdominiak** [SnowdogApps/magento2-menu#52]
Just few things, what we can add in new version:
- method to get product title (right now we need to type product name in PA)
- price formatter - to change output from `227.1200` to `227,00 + currency symbol`

**Comment by Igloczek** [comment]
Internal ticket [DEV-42404]

**Comment by DariuszMaciejewski** [comment]
The changes will be available with the upcoming release.
Related commit: https://github.com/SnowdogApps/magento2-menu/commit/7dbbc6615914d9ca5c871f60acc59df8f60aefd9
