### ISSUE TITLE
Search product hints 

### ISSUE THREAD

**Issue by bartdominiak** [SnowdogApps/magento2-menu#53]
It will be useful to have hints after typed product id (maybe after 3+ chars will be safer)
And also did you think about add SKU instead of ID's? or both?

**Comment by Igloczek** [comment]
Internal ticket [DEV-42403]

**Comment by bartdominiak** [comment]
After backend consultation, we can't add product suggestion/hints. We'll just add SKU instead ID's.

**Comment by bartdominiak** [comment]
Closing this issue. As backend consultation, we will keep ID's because changing this field to SKU may cause an errors for other projects, which has started with ID field. And also binding is working well now on products id.
