### ISSUE TITLE
Readme: "Adding new types of nodes" is incorrect

### ISSUE THREAD

**Issue by denistrator** [SnowdogApps/magento2-menu#58]
"Adding new types of nodes" readme section refers to `view/adminhtml/web/js/category.js` and `view/adminhtml/templates/menu/node_type/category.phtml` but these files were removed.

Please update "Adding new types of nodes", because currently it's not clear how to add a new menu node

**Comment by Igloczek** [comment]
Thanks for reporting, we will update it soon.
Internal ticket [DEV-43122]

**Comment by Igloczek** [comment]
Docs updated.
