### ISSUE TITLE
Mobile menu sub category link goes to undefined

### ISSUE THREAD

**Issue by mageprashant** [SnowdogApps/magento2-menu#65]
Hi,
I am using your extension which works fine in desktop but in mobile view when I click on subcategory link it redirects to an example.com/undefined

Please check given video for more information.
https://www.screencast.com/t/4QxtVtXPZykF

Please help on this asap.

Thanks,

**Comment by Igloczek** [comment]
We don't have JS in this module, `undefined` can't be returned from the PHP based backend, so it's something wrong in your project JS code.

**Comment by mageprashant** [comment]
@Igloczek Thank you for a quick response!
I will check my code.

**Comment by talalus** [comment]
closing this, feel free to re-open it if you have any further questions

**Comment by template-provider** [comment]
@mageprashant : did you find the problem? I am having the same difficulties?
