### ISSUE TITLE
Issue with selecting text in nodes section of backend

### ISSUE THREAD

**Issue by chetanaccorin** [SnowdogApps/magento2-menu#67]
Attempting to drag to select text within Main Menu > Nodes section of the backend results in the entire node being moved instead - 
the only way to change text is to click into the field 
1. backspace or use the keyboard to select all
2. using the mouse to select all, attempts to move node location within the layout

**Steps to reproduce**
Step: 1) Content>Main Menu> Nodes 
Step: 2) Select any node & click the edit button 
Step: 3) try to drag and select text in any of the fields

**Comment by talalus** [comment]
Drag and drop feature for menu item is to change the menu items order and parent/child relations and we are not planning to remove this feature, as you said if you want to select menu text you can edit the menu and select the text from the text field. 
I'm closing this but feel free to re-open it if you have any further questions

**Comment by talalus** [comment]
I'm opening this to check if maybe we can lock the drag and drop while editing the menu or decopule edit form from menu item

**Comment by chetanaccorin** [comment]
@talalus Thanks

**Comment by talalus** [comment]
DEV-internal 46364

**Comment by talalus** [comment]
Thanks @bartdominiak edit form now is not draggable

**Comment by chetanaccorin** [comment]
@talalus @bartdominiak 
Thanks
