### ISSUE TITLE
Clarify documentation about adding a new node type

### ISSUE THREAD

**Issue by juho-jaakkola** [SnowdogApps/magento2-menu#69]
The README says:

> Menu editor is using Vue.js so you need to create a new vue component that has node type code as name in view/adminhtml/web/vue/menu-type and load it in view/adminhtml/templates/menu/nodes.phtml

I have created the template `view/adminhtml/web/vue/menu-type/recommendation.vue` into my custom module. But what exactly does it mean to "load it in `view/adminhtml/templates/menu/nodes.phtml`"?

**Comment by talalus** [comment]
1. `view/adminhtml/web/vue/menu-type.vue` is using [Dynamic Components ](https://vuejs.org/v2/guide/components.html#Dynamic-Components) to load menu custom fields, so in this case the dynamic component will be like
`<component :is="recommendation"></component>`
2. Add recommendation component `"vue!Snowdog_Menu/vue/menu-type/recommendation"`
in [view/adminhtml/templates/menu/nodes.phtml](https://github.com/SnowdogApps/magento2-menu/blob/master/view/adminhtml/templates/menu/nodes.phtml#L41) to register the recommendation component 
3. make sure the component name in view/adminhtml/web/vue/menu-type/recommendation.vue is "recommendation"
```
define(["Vue"], function(Vue) {
    Vue.component("recommendation", {
        template: template,
        props: ['config', 'item']
    });
});
```

**Comment by juho-jaakkola** [comment]
Wait, so do I have to override the whole `view/adminhtml/templates/menu/nodes.phtml` file in my custom module with a version that also has my own vue component?

What if two different custom modules want to add their own node type? It's not possible for them both the override the same template at the same time.

**Comment by talalus** [comment]
Yes for now you need to override `view/adminhtml/templates/menu/nodes.phtml`.
If you have another solution when different custom modules add new node type, your pull request is welcome

**Comment by juho-jaakkola** [comment]
Unfortunately I don't have time enough time in my current project. I will however document the need within my module, so perhaps it can be implemented some time later.

**Comment by Koc** [comment]
@talalus what about adding some method in node type interface like `getVueComponent`? And inside `view/adminhtml/templates/menu/nodes.phtml` collect this components to array. It is much cleaner way

**Comment by talalus** [comment]
@Koc yes I think need to check with Backend dev, but will be great if you can you prepare a MR for this.

**Comment by Januszpl** [comment]
@Igloczek  I think after finishing #84 and #85 I think we should think how we can refactor whole vue part as for sure there it can be done better and during this refactor we should consider this request.

**Comment by andrzejborkowski** [comment]
@juho-jaakkola here is the link with updated [README](https://github.com/SnowdogApps/magento2-menu/blob/2.13.0/README.md) file
