### ISSUE TITLE
Include compiled js file

### ISSUE THREAD

**Issue by giacmir** [SnowdogApps/magento2-menu#7]
The javascript in /master/view/frontend/web/js/navigation.babel.js must be compiled with babel before it can be used by "normal" browsers. This is incompatible with a vanilla Magento2 not using frontools.

Can you add a compiled version in the repository so that this module can be used directly on a plain Magento 2?

**Comment by Igloczek** [comment]
We are not planning to ship this module with transpiled JS code.
Also we are not planning using Less or compiled CSS.

BTW. "normal" browsers understand ES6 - 74% global support 😉

**Comment by giacmir** [comment]
Thanks for you answer. While I understand your position on not including transpiled code I just want to comment that 74% support is still low. This means that one visitor out of four won't be able to have a working navigation menu.

bye

**Comment by Igloczek** [comment]
Our modules are built for our internal needs, we are sharing them as a side project for devs who can benefit from using it, not to work with every possible M2 instance out of the box.

So if something doesn't look good enough for you, fork it and customize for your needs or just don't use it.
