### ISSUE TITLE
Current api implementation incomplete

### ISSUE THREAD

**Issue by Koc** [SnowdogApps/magento2-menu#70]
Hello!

First of all - thank you for free module for menu. I've trying to use Magento in headless mode (frontend based on VueJS). And current rest api miss something crucial things, like:

https://github.com/SnowdogApps/magento2-menu/blob/master/etc/webapi.xml#L9
1. it is logical retrieve nodes using GET method and by string identifier, not by id. Something like `url="/V1/menus/:identifier/nodes"`
2. for now we haven't any additional information inside response (node label, node url, etc). Would be nice add some key-value collection with additional data.
3. not sure that anonymous users even has access to this methods because resource restriction.

**Comment by kiber** [comment]
Changes are available in release/2.10.0
