### ISSUE TITLE
Vue - duplicate keys detected found in <SnowdogMenu>

### ISSUE THREAD

**Issue by tiberiur** [SnowdogApps/magento2-menu#71]
From time to time while adding/editing items in the menu, randomly, this error pop up https://i.imgur.com/UUfzdjN.png.

The error makes the menu disappear on the front and there are some empty items in the admin https://i.imgur.com/xch0sDu.png.

The problem persist on M2.2.4 / M2.3. Windows / Linux too.

**Comment by talalus** [comment]
internat-ticket:48712

**Comment by talalus** [comment]
@tiberiur fix in 2.8.1
