### ISSUE TITLE
Product node image not working

### ISSUE THREAD

**Issue by jahvi** [SnowdogApps/magento2-menu#73]
The product image is not rendering anything even though the product does have an image associated to it.

**Steps to reproduce:**
1. Create a new product node and assign a product with image.
2. Change `menu/node_type/product.phtml` template to echo the included `$productImage` variable.

**Expected result:**

The product image URL should show up.

**Actual result:**

Nothing is outputted.

--

I found that the problem is the `fetchImageData` function in `Model/ResourceModel/NodeType/Product.php` not getting the thumbnail data even though it's being added as an attribute to select in the collection but I didn't get further than that.

**Comment by jahvi** [comment]
My bad, I tested on both 2.2.6 and 2.3 and got the same issue.

**Comment by Igloczek** [comment]
Thanks, we will check it.

Internal ticket DEV-49462

**Comment by dariuszmaciejewski** [comment]
The bugfix has been merged into the develop branch.

**Comment by jahvi** [comment]
Thanks!

**Comment by bacondeveloper** [comment]
Do we know when this will be released into the release branch? I've tested the develop branch and it works perfectly!

**Comment by Igloczek** [comment]
@jahvi @bacondeveloper Fix released as v2.8.2

**Comment by jahvi** [comment]
Nice thanks for looking into it!

**Comment by bacondeveloper** [comment]
Brilliant thank you :)
