### ISSUE TITLE
Include subcategories

### ISSUE THREAD

**Issue by DanieliMi** [SnowdogApps/magento2-menu#75]
Hey,
is it possible to implement a functionality to import categories including subcategories as nodes? Maybe even with specifying until which level you want to include subcategories. It would be really handy if you could import them in case you have a whole bunch of subcategories. Inserting all these nodes separately is lots of effort.

**Comment by jg-development** [comment]
+1

**Comment by digiltd** [comment]
@jg-development this already works, add the "category child" node as the child of a regular category node (note: I don't think this is a requirement, but should help you get your head around it)

**Comment by jg-development** [comment]
ahh thx .. will try

**Comment by template-provider** [comment]
for me it works

**Comment by andy1786** [comment]
for me works, only the ordering with drag and drop is not working

**Comment by andrzejborkowski** [comment]
Import categories and subcategories as menu nodes was released recently in [2.16.0](https://github.com/SnowdogApps/magento2-menu/releases/tag/2.16.0)
