### ISSUE TITLE
Unable to view/select from all dropdown options

### ISSUE THREAD

**Issue by jasuten** [SnowdogApps/magento2-menu#78]
The dropdown in the admin gets cut off so you can't select from all the categories. Tested it in Firefox and Chrome. See attached.

<img width="800" alt="screen shot 2019-02-13 at 2 03 05 pm" src="https://user-images.githubusercontent.com/204446/52683837-4626e780-2f98-11e9-9d99-9a4caa15beaa.png">

**Comment by Igloczek** [comment]
Thanks for the report, the bug was fixed in #79 and is already released as version 2.8.3
