### ISSUE TITLE
Prepending store url in Custom Url nodes should be optional

### ISSUE THREAD

**Issue by lukeromanowicz** [SnowdogApps/magento2-menu#80]
Right now, we are not able to set a custom url node that would redirect to a third party page. It is caused by prepending store url in CustomUrl Block:

https://github.com/SnowdogApps/magento2-menu/blob/75b9ec2e9ee858d41cf11b2fdd724dc89b49f5f3/Block/NodeType/CustomUrl.php#L84

I would be nice to make it optional with enabled by default to keep the backward compatibility.

**Comment by jochhop** [comment]
Thanks for your suggestion @lukeromanowicz an internal ticket has been created to check the issue DEV-53114

**Comment by dariuszmaciejewski** [comment]
The change has been merged into the develop branch (https://github.com/SnowdogApps/magento2-menu/commit/fd285d2ffd49fe2075672fca20af595dc0131fd6).
