### ISSUE TITLE
Using a product node displays original image

### ISSUE THREAD

**Issue by tomkingfisher** [SnowdogApps/magento2-menu#95]
When using a product node it displays the full original image rather than a resized and optimised version.

Because the menu is on ever page the images are being loaded on every page and because they are the original images it is slowing the site down.

Is there a way to be able to choose an image role or specify a role so that images are optimised and resized?

**Comment by kiber** [comment]
@tomkingfisher changes are merged with the **develop** branch and it will be in the next release.
You can use
`$resizedProductImage = $block->getResizedProductImage($nodeId, '300', '300');`
in template file to get resized product image

**Comment by andrzejborkowski** [comment]
@tomkingfisher the issue has been resolved in the latest [2.13.0 release](https://github.com/SnowdogApps/magento2-menu/releases/tag/2.13.0)
