### ISSUE TITLE
Nodes are deleted and recreated every time a menu is saved

### ISSUE THREAD

**Issue by natedawg92** [SnowdogApps/magento2-menu#97]
## Background
Every time a Menu is saved the Nodes in that menu are deleted and Recreated

## UAC 
- [ ] Nodes are not Deleted and recreated every time a menu is saved

## Spec
- Update https://github.com/SnowdogApps/magento2-menu/blob/master/Controller/Adminhtml/Menu/Save.php#L136 to check for the node IDs in the `$existingNodes` array rather than a regex pattern it will never match

**Comment by kiber** [comment]
@natedawg92 thanks for reporting issue. I will check it

**Comment by natedawg92** [comment]
@kiber Any progress on this issue and the associated PR #98

**Comment by kiber** [comment]
@natedawg92 thanks for your PR, these changes will be in the next release.
